
### signup user
POST http://localhost:8080/api/signup
Content-Type: application/json

{
    "fullname": "firstero",
    "email": "firstero@org",
    "password": "123456",
    "workspace": "acme"
}

### signin user
# @name signin
POST http://localhost:8080/api/signin
Content-Type: application/json

{
    "fullname": "firstero",
    "email": "firstero@org",
    "password": "123456"
}

### create another user
POST http://localhost:8080/api/signup
Content-Type: application/json

{
    "fullname": "Alice",
    "email": "Alice@org",
    "password": "123456",
    "workspace": "acme"
}

@token = {{signin.response.body.token}}
### get chat list
POST http://localhost:8080/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "acme",
    "members": [1, 2],
    "public": true
}

### create another chat
POST http://localhost:8080/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "members": [1, 2],
    "public": false
}
### get chat list
GET http://localhost:8080/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

### get user list
GET http://localhost:8080/api/users
Authorization: Bearer {{token}}
Content-Type: application/json


### upload files
POST http://localhost:8080/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="DeathNote-L.png"
Content-Type: application/octet-stream

< /Users/firstero/Downloads/DeathNote-L.png
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"

hello, world!
--MyBoundary--

### download files
GET http://localhost:8080/api/files/1/933/58a/63d6b0571dd46855d6f64e045a30f71d2a.png